### ISSUE TITLE
linopy fix

### ISSUE THREAD

**Issue by coroa** [UNSW-CEEM/Battery-Optimisation-Benchmarking#1]
You are right, linopy is still too alpha for directly comparing it with the other implementations, but anyway, just had a short look and what is going wrong is https://github.com/PyPSA/linopy/issues/57 .

ie. `variable / scalar` is not dispatching to the correct method and changing variable labels instead of coefficients in a linear expression.

```python
    intertemp_soc_lhs = (
        soc_mwh
        - soc_mwh.shift(datetime=1)
        - charge_mw * (charge_eff * tau)
        + discharge_mw * (tau / discharge_eff)
    ).isel(datetime=slice(1, None))
```
will work correctly; ie you either do `variable * scalar` or `scalar * variable`.

To understand why the shift is necessary, that is a pandas/xarray feature that they align data on their index (the first column, like the labels) automatically.

Just consider the very simple example below:
```python
In [1]: import pandas as pd

In [2]: s = pd.Series([1, 2, 3])

In [3]: s
Out[3]:
0    1
1    2
2    3
dtype: int64

In [4]: s.loc[1:]
Out[4]:
1    2
2    3
dtype: int64

In [5]: s.shift(1)
Out[5]:
0    NaN
1    1.0
2    2.0
dtype: float64

In [6]: s - s.loc[1:]
Out[6]:
0    NaN
1    0.0
2    0.0
dtype: float64

In [7]: s - s.shift(1)
Out[7]:
0    NaN
1    1.0
2    1.0
dtype: float64
```

**Comment by prakaa** [comment]
Thanks @coroa. Will hopefully have time to correct in the next couple of weeks.

**Comment by prakaa** [comment]
Thanks very much @coroa, working now. I will update the README
